name: Build clover debian package

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-20.04
#    container: ros:noetic-ros-base
    services:
      rpios:
        image: ghcr.io/carlosperate/qemu-rpi-os-lite:buster-latest
        ports: ["5022:5022"]
    steps:
      - name: Wait 2m30s for the docker image to start up QEMU and Raspberry Pi OS
        run: sleep 150
      - name: Check processor architecture
        uses: appleboy/ssh-action@master
        with:
          host: rpios
          username: pi
          password: raspberry
          port:  ${{ job.services.rpios.ports[5022] }}
          script: |
            echo Architecture:
            dpkg-architecture -q DEB_BUILD_ARCH
      - name: Install ROS
        uses: appleboy/ssh-action@master
        with:
          host: rpios
          username: pi
          password: raspberry
          port: ${{ job.services.rpios.ports[5022] }}
          command_timeout: 90m
          script: |
            sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu buster main" > /etc/apt/sources.list.d/ros-noetic.list'
            sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
            sudo apt update
            sudo apt-get install -y python-rosdep python-rosinstall-generator python-wstool python-rosinstall build-essential cmake
            sudo rosdep init && rosdep update
            mkdir ~/ros_catkin_ws && cd ~/ros_catkin_ws
            rosinstall_generator ros_comm --rosdistro noetic --deps --wet-only --tar > noetic-ros_comm-wet.rosinstall
            wstool init src noetic-ros_comm-wet.rosinstall
            rosdep install -y --from-paths src --ignore-src --rosdistro noetic -r --os=debian:buster
            sudo src/catkin/bin/catkin_make_isolated --install -DCMAKE_BUILD_TYPE=Release --install-space /opt/ros/noetic -j1 -DPYTHON_EXECUTABLE=/usr/bin/python3
            source /opt/ros/noetic/setup.bash
            roscore
#      - name: Checkout repository
#        uses: actions/checkout@v2


#
#      - name: Install catkin
#        run: |
#          cd / && ./ros_entrypoint.sh
#          apt-get update
#          apt-get install -y ros-noetic-catkin python3-catkin-tools python3-osrf-pycommon
#
#      - name: Setup catkin workspace
#        run: |
#          mkdir -p ~/catkin_ws/src
#          cd ~/catkin_ws
#          /bin/bash -c "source /opt/ros/noetic/setup.bash && catkin_make"
#
#      - name: Build catkin package
#        run: |
#          cd ~/catkin_ws/src
#          cp -r $GITHUB_WORKSPACE .
#          cd ~/catkin_ws
#          /bin/bash -c "source ~/catkin_ws/devel/setup.bash && catkin_make"
#
#      - name: Install builder dependencies
#        run: |
#          apt-get install -y python3-bloom fakeroot debhelper dpkg-dev
#
#      - name: Init rosdep
#        run: |
#          rm /etc/ros/rosdep/sources.list.d/20-default.list
#          sudo rosdep init
#          rosdep update
#
#      - name: Build deb package
#        run: |
#          /bin/bash -c "source ~/catkin_ws/devel/setup.bash && roscd clover_app"
#          bloom-generate rosdebian
#          fakeroot debian/rules binary
