name: Build clover debian package

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-20.04
    container: ros:noetic-ros-base
    steps:
      - uses: actions/checkout@v2
      - name: Install catkin
        run: |
          cd / && ./ros_entrypoint.sh
          apt-get update
          apt-get install -y ros-noetic-catkin python3-catkin-tools python3-osrf-pycommon
          /bin/bash -c "source /opt/ros/noetic/setup.bash && catkin_make"

