name: Build clover debian package

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-20.04
    container: ros:noetic-ros-base
    steps:
      - name: Install dependencies
        run: |
          cd / && ./ros_entrypoint.sh
